import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import {
  ShieldAlert,
  Filter,
  Search,
  RefreshCw,
  ArrowRight,
  User,
  AlertTriangle,
  CheckCircle2,
} from 'lucide-react';
import { amlApi } from '../../api/aml';
import { AlertStatus } from '../../types/aml';
import { RiskLevel } from '../../types/customer';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { Badge } from '../../components/ui/Badge';
import { formatDate, formatScore } from '../../lib/utils';

export const AlertsQueuePage: React.FC = () => {
  const [selectedStatus, setSelectedStatus] = useState<AlertStatus | 'ALL'>('ALL');
  const [selectedRisk, setSelectedRisk] = useState<RiskLevel | 'ALL'>('ALL');
  const [customerFilter, setCustomerFilter] = useState('');

  const statusParam = selectedStatus === 'ALL' ? undefined : selectedStatus;
  const riskParam = selectedRisk === 'ALL' ? undefined : selectedRisk;

  const {
    data: alerts,
    isLoading,
    refetch,
    isFetching,
  } = useQuery({
    queryKey: ['alerts', statusParam, riskParam],
    queryFn: () => amlApi.getAllAlerts(statusParam, riskParam),
    refetchInterval: 10000,
  });

  const filteredAlerts = alerts?.filter((a) => {
    if (!customerFilter.trim()) return true;
    return a.customerUuid?.toLowerCase().includes(customerFilter.trim().toLowerCase());
  });

  return (
    <div className="max-w-7xl mx-auto space-y-8 pb-12">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-xs font-mono text-rose-400 uppercase tracking-wider mb-1">
            <ShieldAlert className="w-3.5 h-3.5" />
            <span>Compliance Monitoring Queue</span>
          </div>
          <h1 className="text-2xl font-bold text-slate-100">AML Alerts Queue</h1>
          <p className="text-xs text-slate-400 mt-1">
            Real-time compliance alerts generated by the Isolation Forest anomaly detector & deterministic rule matrix.
          </p>
        </div>

        <button
          onClick={() => refetch()}
          className="self-start sm:self-center px-3 py-2 rounded-lg bg-background-elevated hover:bg-background-hover text-slate-300 hover:text-white border border-border text-xs font-medium transition-colors flex items-center gap-2"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${isFetching ? 'animate-spin text-brand-500' : ''}`} />
          <span>Refresh Queue</span>
        </button>
      </div>

      {/* Filter Controls Bar */}
      <Card>
        <CardContent className="p-4 space-y-4">
          <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
            {/* Status Filters */}
            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-xs font-medium text-slate-400 mr-1 flex items-center gap-1">
                <Filter className="w-3.5 h-3.5" />
                Status:
              </span>
              {(['ALL', 'OPEN', 'UNDER_REVIEW', 'RESOLVED', 'FALSE_POSITIVE'] as const).map((status) => (
                <button
                  key={status}
                  onClick={() => setSelectedStatus(status)}
                  className={`px-3 py-1 rounded-lg text-xs font-medium transition-all ${
                    selectedStatus === status
                      ? 'bg-brand-500 text-white shadow-sm shadow-brand-500/30'
                      : 'bg-background-surface text-slate-400 hover:text-slate-200 border border-border'
                  }`}
                >
                  {status}
                </button>
              ))}
            </div>

            {/* Risk Filters */}
            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-xs font-medium text-slate-400 mr-1">Risk Tier:</span>
              {(['ALL', 'HIGH', 'MEDIUM', 'LOW'] as const).map((risk) => (
                <button
                  key={risk}
                  onClick={() => setSelectedRisk(risk)}
                  className={`px-3 py-1 rounded-lg text-xs font-medium transition-all ${
                    selectedRisk === risk
                      ? risk === 'HIGH'
                        ? 'bg-rose-500 text-white'
                        : risk === 'MEDIUM'
                        ? 'bg-amber-500 text-slate-950 font-bold'
                        : risk === 'LOW'
                        ? 'bg-emerald-500 text-white'
                        : 'bg-brand-500 text-white'
                      : 'bg-background-surface text-slate-400 hover:text-slate-200 border border-border'
                  }`}
                >
                  {risk}
                </button>
              ))}
            </div>
          </div>

          {/* Customer Filter Search Bar */}
          <div className="pt-2 border-t border-border/60 flex items-center">
            <div className="relative flex-1 max-w-md">
              <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2 pointer-events-none" />
              <input
                type="text"
                value={customerFilter}
                onChange={(e) => setCustomerFilter(e.target.value)}
                placeholder="Filter alerts by Customer UUID..."
                className="w-full bg-background-surface border border-border rounded-lg pl-9 pr-4 py-1.5 text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-brand-500 font-mono"
              />
            </div>
            {customerFilter && (
              <button
                onClick={() => setCustomerFilter('')}
                className="ml-2 text-xs text-slate-400 hover:text-white"
              >
                Clear
              </button>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Alerts Table */}
      <Card>
        <CardHeader>
          <CardTitle>
            <span>Alert Queue Records</span>
            <span className="text-xs font-mono text-slate-400 font-normal ml-2">
              ({filteredAlerts?.length ?? 0} matches)
            </span>
          </CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          {isLoading ? (
            <div className="p-12 text-center text-xs text-slate-400 flex flex-col items-center gap-3">
              <RefreshCw className="w-6 h-6 text-brand-500 animate-spin" />
              <span>Loading compliance queue records...</span>
            </div>
          ) : !filteredAlerts || filteredAlerts.length === 0 ? (
            <div className="p-12 text-center text-xs text-slate-400 space-y-2">
              <CheckCircle2 className="w-10 h-10 text-emerald-400/60 mx-auto" />
              <p className="text-slate-200 font-medium">No Alerts Found</p>
              <p className="text-slate-500">
                No alerts match the selected status, risk tier, and customer filters.
              </p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead className="bg-background-surface/80 border-b border-border text-slate-400 font-mono uppercase tracking-wider">
                  <tr>
                    <th className="px-6 py-3">Created</th>
                    <th className="px-6 py-3">Risk Tier</th>
                    <th className="px-6 py-3">Status</th>
                    <th className="px-6 py-3">Hybrid Score</th>
                    <th className="px-6 py-3">ML / Rule</th>
                    <th className="px-6 py-3">Customer UUID</th>
                    <th className="px-6 py-3">Reason Codes</th>
                    <th className="px-6 py-3 text-right">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border/60">
                  {filteredAlerts.map((alert) => (
                    <tr key={alert.alertUuid} className="hover:bg-background-elevated/40 transition-colors">
                      <td className="px-6 py-4 font-mono text-slate-400 whitespace-nowrap">
                        {formatDate(alert.createdAt)}
                      </td>
                      <td className="px-6 py-4">
                        <Badge variant="risk" riskLevel={alert.riskLevel} size="sm" />
                      </td>
                      <td className="px-6 py-4">
                        <Badge variant="status" status={alert.status} size="sm" />
                      </td>
                      <td className="px-6 py-4 font-mono font-bold text-slate-100">
                        {formatScore(alert.hybridScore, 4)}
                      </td>
                      <td className="px-6 py-4 font-mono text-slate-400 whitespace-nowrap">
                        <span className="text-cyan-400">{formatScore(alert.anomalyScore, 3)}</span>
                        {' / '}
                        <span className="text-indigo-400">{formatScore(alert.ruleScore, 3)}</span>
                      </td>
                      <td className="px-6 py-4 font-mono text-slate-300">
                        {alert.customerUuid ? (
                          <Link
                            to={`/customers/${alert.customerUuid}`}
                            className="hover:text-indigo-400 underline flex items-center gap-1"
                          >
                            <span>{alert.customerUuid.substring(0, 8)}...</span>
                          </Link>
                        ) : (
                          'N/A'
                        )}
                      </td>
                      <td className="px-6 py-4 max-w-xs truncate text-slate-300">
                        {alert.reasons?.join(', ') || 'Rule threshold exceeded'}
                      </td>
                      <td className="px-6 py-4 text-right whitespace-nowrap">
                        <Link to={`/alerts/${alert.alertUuid}`}>
                          <Button variant="outline" size="sm">
                            <span>Investigate</span>
                            <ArrowRight className="w-3 h-3 ml-1" />
                          </Button>
                        </Link>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};
