package com.finvigil.common.enums;

public enum AuditAction {
    CUSTOMER_REGISTERED,
    CUSTOMER_LOGIN,
    CREDIT_APPLICATION_CREATED,
    CREDIT_DECISION_RECEIVED,
    TRANSACTION_INITIATED,
    TRANSACTION_COMPLETED,
    AML_ALERT_GENERATED,
    AML_ALERT_STATUS_UPDATED,
    EMPLOYEE_REGISTERED,
    EMPLOYEE_LOGIN,
    EMPLOYEE_LOGIN_FAILED
}

